@echo off
setlocal enabledelayedexpansion

echo Creating directories...
if not exist "screens" mkdir "screens"

echo Downloading Screen 1: Login - Sistem Rekomendasi Varietas Unggulan
curl -L "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sXzhmNGM0ZWZiODY3ZDQxZDRiMmFiZTE5ZDc5OTI3NDAxEgsSBxCn4KrxvxEYAZIBJAoKcHJvamVjdF9pZBIWQhQxNjYyNzI5NjIzMDI5NTA1OTA2Nw&filename=&opi=89354086" -o "screens\1_login_code.html"
curl -L "https://lh3.googleusercontent.com/aida/ADBb0uilnLdoveI1RB-f2Ge-hsbZ1LYBj2jVnb1PGsXapQ6glUG0U2uibnHxvk313WDUV8nGXNZd3pyJAI5XX1Vt2n-3Hf1JHQ3hNzsi2NfKbo123t5y_yPs10ddwEF544QkzHFEB9VV1xOb_SX1uzx558BUpc_qzBcYelc6jY4VULrqdLn6kx3IZHzxxx5lXwD8LUv1MHXnsxbj2UsXWQ9LkcK4M-h824loLSaV_0FfVxyPJYoY-ntE3rr2CNvi" -o "screens\1_login_screenshot.png"

echo Downloading Screen 2: Kelola Data - Dataset Tanaman
curl -L "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sXzE0YjM3YTA4ODgxNzRjZmY5MWI1MGIxYWMzOGI2MjkzEgsSBxCn4KrxvxEYAZIBJAoKcHJvamVjdF9pZBIWQhQxNjYyNzI5NjIzMDI5NTA1OTA2Nw&filename=&opi=89354086" -o "screens\2_kelola_data_code.html"
curl -L "https://lh3.googleusercontent.com/aida/ADBb0uiIW1CGzLbSZ-fPMtGDvM231c95vLwBPz42gd8ogrf4EdWQ7ADw-sF1mJ7wEzWF9KQuUSCkbotYdFr5HhuDVfBGBhjTOT-jjJfLP_NZ112RUBZyXkG2XMkXEoHpku5oquLx_ymB4EqyoYyVxxvtLoouYb30OPiGGf4TzXT4eCQL0Q7nUhJ8RlYrhDJI6ymLzGf6qc5sKAWv2pXKHndPVr6u6Aj5MB1Bqm4BX0_tnOSarwh2x2s0RB8-oMhv" -o "screens\2_kelola_data_screenshot.png"

echo Downloading Screen 3: Dashboard - Sistem Rekomendasi
curl -L "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sX2MzNWIzNGFkYjBjOTQwNWJhODUzZDc0MDE4MjZlMTUyEgsSBxCn4KrxvxEYAZIBJAoKcHJvamVjdF9pZBIWQhQxNjYyNzI5NjIzMDI5NTA1OTA2Nw&filename=&opi=89354086" -o "screens\3_dashboard_code.html"
curl -L "https://lh3.googleusercontent.com/aida/ADBb0ujB-ZpPKNEDcYMMpsDxTuNVmZv_k9qR-yNdNbCkjrN2jHnhNhpyjRQlZQC7xaJD6QQGvg7SnQ26bREqEluKySbvquy4ySthx_SNvVHuvDR9_IXcuAy14e4l2nK2NZ-krsW7yhdMlE4y_4GwduRCjMk5TcCyg0eM0QPJkXWbglByx3dvRBPwP5YDMQ8Rw6qHAQmD9yMhBKm-eJt7VH-EvmIZcwbCFCL4txmMXwr_AO_W-pJRHN9XJbdXGwG_" -o "screens\3_dashboard_screenshot.png"

echo Downloading Screen 4: Hasil Klasifikasi ^& Evaluasi
curl -L "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sXzgyNTlhNzE3ODdmYjQ0YjRhMWExMzgwYzA3NjY0ZWI2EgsSBxCn4KrxvxEYAZIBJAoKcHJvamVjdF9pZBIWQhQxNjYyNzI5NjIzMDI5NTA1OTA2Nw&filename=&opi=89354086" -o "screens\4_hasil_klasifikasi_code.html"
curl -L "https://lh3.googleusercontent.com/aida/ADBb0uhUjTXEebqTOv3TEPnA3Yk6pJR8Fk5184PHAe6fUtFRus39qzElpnyktFjdLX_ZO3KxryQXtbHHYsNXx6ZxJkWxXjNeOIFfqI3Y8asQp2IX_VQnyuofBIogAcwxkKk0DJtYgObx2SZQduzvn8u2IZbkRZBns7KujFgxlNnu3h_Q5eLBdwtwckldyWi9Vk4C2lhIek2_AajXThKKDq-ApdSfRKf6axG80QIM4C-tIxuT1Z7w-fjHUgl76scX" -o "screens\4_hasil_klasifikasi_screenshot.png"

echo Downloading Screen 5: Form Prediksi - Rekomendasi Varietas
curl -L "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sXzhkZjQ1YjllZTgwNzQ1YTg5YzIyNmRiZDg2ZjZiOWVlEgsSBxCn4KrxvxEYAZIBJAoKcHJvamVjdF9pZBIWQhQxNjYyNzI5NjIzMDI5NTA1OTA2Nw&filename=&opi=89354086" -o "screens\5_form_prediksi_code.html"
curl -L "https://lh3.googleusercontent.com/aida/ADBb0ujY_yR9hzZ6R_lNN8ryjAaE74DqhM9RnxTMYlMQ4dOasWqPtrfhjnp91fz0dHIIb_ZYxZVE5bv4wu8rsUTIU1n-Zbz7nESGr792i6s2issJGVfadSP4gokKbDyVcBdSuLCuzFv_hsoDuTdJijk6kG1OyGHQpnrKVd46i6QSIYLPRPff3R1g68FRc4ukdEaD-GXBpDRFYfsCBt45CMXD1mAEGz_MJGmubASRDfReUTgmrPoa0o_sEMCTD0P6" -o "screens\5_form_prediksi_screenshot.png"

echo Download finished!
pause
